/**
* For grams, convert from label as follows:
'càc' : 5 g
'dosette' : 15 g
'feuille' : 20 g
'gousse' : 6 g
'pièce' : 50 g
'pincée': 1 g
'tranches' : 40 g
If not in this list, set to 10
*/
export interface MeasureItf {
    idTmp: string // generate a unique id for each measure, with a four-padded digit number e.g., "M0001"
    foodId: string // Will be the food name attribute, resolved to ObjectId during import
    label: string // will be the unit from SeedRecipe.ingredient
    grams: number
    isDefault: boolean // Always false

}

export interface Ingredient {
    ingredient: string
    unit: string

}

export const seedRecipes: Ingredient[] = [
    { ingredient: 'Ail', unit: 'gousse' },
    { ingredient: 'Amandes entières', unit: 'g' },
    { ingredient: 'Arôme de banane', unit: 'dosette' },
    { ingredient: 'Aubergine, pulpe et peau, rôtie/cuite au four', unit: 'g' },
    { ingredient: 'Bacon fumé JUSTIN BRIDOU, 16 tranches soit 160g', unit: 'g' },
    { ingredient: 'Banane, pulpe, crue 100 gr', unit: 'g' },
    { ingredient: 'Beurre de cacahuètes', unit: 'g' },
    { ingredient: 'Beurre demi sel', unit: 'g' },
    { ingredient: 'Blé Ebly portion 65 gr sec', unit: 'g' },
    { ingredient: 'Bouillon', unit: 'ml' },
    { ingredient: 'Brocoli surgelé Bio U', unit: 'g' },
    { ingredient: 'Butternut', unit: 'g' },
    { ingredient: 'Carotte', unit: 'g' },
    { ingredient: 'Champignons', unit: 'g' },
    { ingredient: 'Chipolatas U (par 6, 330 gr)', unit: 'g' },
    { ingredient: 'Chocolat Pépites Koro 70%', unit: 'g' },
    { ingredient: 'Chou frisé', unit: 'g' },
    { ingredient: 'Chou-fleur surgelé', unit: 'g' },
    { ingredient: 'Ciboulette', unit: 'g' },
    { ingredient: 'Concombre, pulpe, cru', unit: 'g' },
    { ingredient: 'Coquillettes 1/2 Complètes', unit: 'g' },
    { ingredient: 'Cornichons', unit: 'pièce' },
    { ingredient: 'Courgette, pulpe et peau, crue', unit: 'g' },
    { ingredient: 'Couscous 1/2 complet', unit: 'g' },
    { ingredient: 'Crème liquide entière U bio', unit: 'ml' },
    { ingredient: 'Crème Soja liquide', unit: 'ml' },
    { ingredient: 'Crevettes', unit: 'g' },
    { ingredient: 'Crozets', unit: 'g' },
    { ingredient: 'Cumin', unit: 'g' },
    { ingredient: 'Curcuma', unit: 'g' },
    { ingredient: 'Curry', unit: 'g' },
    { ingredient: 'Dés de jambon Herta Nature  2x75 gr', unit: 'g' },
    { ingredient: 'Double concentré de tomates 3x70g', unit: 'g' },
    { ingredient: 'Eau', unit: 'ml' },
    { ingredient: 'Échalote', unit: 'pièce' },
    { ingredient: 'Epices à couscous', unit: 'càc' },
    { ingredient: 'Epices à couscous', unit: 'g' },
    { ingredient: 'Epinards en branche surgelés', unit: 'g' },
    { ingredient: 'Farine T65', unit: 'g' },
    { ingredient: 'Feta', unit: 'g' },
    { ingredient: 'Fromage blanc nature 3% MG (100 gr)', unit: 'g' },
    { ingredient: 'Fromage Croque emmental x20 - 340 gr', unit: 'tranches' },
    { ingredient: 'Fromage de madame Loïc', unit: 'g' },
    { ingredient: 'Fromage tartare', unit: 'g' },
    { ingredient: 'Gingembre', unit: 'g' },
    { ingredient: 'Gnocchi à poêler U 300 gr', unit: 'g' },
    { ingredient: 'Graines de lin', unit: 'g' },
    { ingredient: 'Granola Noix & Graines U Céréales', unit: 'g' },
    { ingredient: 'Gruyère', unit: 'g' },
    { ingredient: 'Haricots Blanc 280 gr', unit: 'g' },
    { ingredient: 'Haricots noirs 230 gr', unit: 'g' },
    { ingredient: 'Herbe de provence', unit: 'g' },
    { ingredient: 'Huile de sésame', unit: 'ml' },
    { ingredient: 'Huile de tournesol', unit: 'ml' },
    { ingredient: 'Huile de tournesol', unit: 'g' },
    { ingredient: 'Jambons 4 tranches 140 gr', unit: 'tranches' },
    { ingredient: 'Jus de citron', unit: 'ml' },
    { ingredient: 'Lait demi-écrémé', unit: 'ml' },
    { ingredient: 'Lait Entier', unit: 'ml' },
    { ingredient: 'Laitue', unit: 'feuille' },
    { ingredient: 'Lasagnes PANZANI', unit: 'feuille' },
    { ingredient: 'Lentilles corails', unit: 'g' },
    { ingredient: 'Lentilles vertes', unit: 'g' },
    { ingredient: 'Levure de bière en paillettes', unit: 'dosette' },
    { ingredient: 'Levure de bière en paillettes', unit: 'g' },
    { ingredient: 'Maïs sans sucre ajouté 140 gr', unit: 'g' },
    { ingredient: 'Maizena', unit: 'g' },
    { ingredient: 'Mayonnaise', unit: 'g' },
    { ingredient: 'Miel de printemps', unit: 'càc' },
    { ingredient: 'Miso (sachet 22 gr)', unit: 'g' },
    { ingredient: 'Moutarde', unit: 'g' },
    { ingredient: 'Moutarde', unit: 'ml' },
    { ingredient: 'Mozarella', unit: 'g' },
    { ingredient: 'Nouilles en nids', unit: 'g' },
    { ingredient: 'Oeuf entier', unit: 'pièce' },
    { ingredient: 'Oignon', unit: 'pièce' },
    { ingredient: 'Oignon', unit: 'g' },
    { ingredient: 'Origan', unit: 'g' },
    { ingredient: 'Pain de mie U (500 g/24 tranches)', unit: 'tranches' },
    { ingredient: 'Paprika', unit: 'g' },
    { ingredient: 'Parmesan', unit: 'g' },
    { ingredient: 'Patate douce, crue', unit: 'g' },
    { ingredient: 'Pâte brisée maison (280 gr)', unit: 'pièce' },
    { ingredient: 'Pesto aux fanes de radis (maison)', unit: 'g' },
    { ingredient: 'Petit Suisse 60 gr', unit: 'pièce' },
    { ingredient: 'Petits pois surgelés', unit: 'g' },
    { ingredient: 'Piment', unit: 'pincée' },
    { ingredient: 'Poireau, cru', unit: 'g' },
    { ingredient: 'Pois cassés (230 gr)', unit: 'g' },
    { ingredient: 'Poivre', unit: 'g' },
    { ingredient: 'Poivron rouge, cru', unit: 'g' },
    { ingredient: 'Pomme (fruit)', unit: 'pièce' },
    { ingredient: 'Pomme de terre crue', unit: 'g' },
    { ingredient: 'Potimarron', unit: 'g' },
    { ingredient: 'Poulet, blanc, cru', unit: 'g' },
    { ingredient: 'Protéines de soja Vantastic', unit: 'g' },
    { ingredient: 'Psyllium', unit: 'dosette' },
    { ingredient: 'Quinoa Trio en vrac', unit: 'g' },
    { ingredient: 'Raz-el-Hanout', unit: 'càc' },
    { ingredient: 'Raz-el-Hanout', unit: 'g' },
    { ingredient: 'Reblochon petit 240 gr', unit: 'g' },
    { ingredient: 'Ricotta (250 gr)', unit: 'g' },
    { ingredient: 'Riz Basmati semi complet', unit: 'g' },
    { ingredient: 'Rôti de porc FLEURY MICHON 210 gr 6 tranches', unit: 'g' },
    { ingredient: 'Sel', unit: 'g' },
    { ingredient: 'Sel', unit: 'pincée' },
    { ingredient: 'Soja crispies au cacao Koro', unit: 'dosette' },
    { ingredient: 'Son d\'avoine Markal', unit: 'g' },
    { ingredient: 'Sucre de canne Blond', unit: 'g' },
    { ingredient: 'Tempeh à cuisiner 200 gr', unit: 'g' },
    { ingredient: 'Thon entier au naturel 140 gr', unit: 'g' },
    { ingredient: 'Tomate grappe, crue', unit: 'g' },
    { ingredient: 'Tomates entières en conserve 400 g', unit: 'g' },
    { ingredient: 'Tortilla de blé complete (géante 58 gr)', unit: 'pièce' },
    { ingredient: 'Tortilla de blé nature (grande 41 gr)', unit: 'pièce' },
    { ingredient: 'Viande hachée 5 %', unit: 'g' },
    { ingredient: 'Vinaigre balsamique', unit: 'ml' },
    { ingredient: 'Vinaigre de cidre', unit: 'ml' },
    { ingredient: 'Whey nutripure', unit: 'g' },
    { ingredient: 'Flocons d\'avoine', unit: 'g' },
    { ingredient: 'Poivron grillés à l\'huile 190 gr', unit: 'g' },
    { ingredient: 'Son d\'avoine Markal', unit: 'g' },
]
