import { CreateFoodDto } from '../src/api/food/dto/food.dto';

export const seedFoods: CreateFoodDto[] = [
    {
        name: 'Amandes entières',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 600, proteins: 22.6, fats: 51.3, carbohydrates: 9.51, sugars: 4.2, fibers: 12.5, salt: 0},
        needReview: false,
        category: 'Noix',
    },
    {
        name: 'Aubergine, pulpe et peau, rôtie/cuite au four',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 33.8, proteins: 1.31, fats: 0, carbohydrates: 3.83, sugars: 0, fibers: 1.9, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Bacon fumé JUSTIN BRIDOU, 16 tranches soit 160g',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 116, proteins: 23, fats: 2.5, carbohydrates: 0.3, sugars: 0.2, fibers: 0, salt: 0},
        needReview: false,
        category: 'Charcuterie',
    },
    {
        name: 'Banane, pulpe, crue 100 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 90.5, proteins: 1.06, fats: 0, carbohydrates: 19.7, sugars: 3.8, fibers: 2.7, salt: 0},
        needReview: false,
        category: 'Fruit',
    },
    {
        name: 'Betterave en sachet',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 44, proteins: 0, fats: 0.1, carbohydrates: 7.2, sugars: 6.7, fibers: 0, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Beurre de cacahuètes',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 635, proteins: 29, fats: 53, carbohydrates: 9.3, sugars: 4.5, fibers: 5.6, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Beurre demi sel',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 726, proteins: 0.6, fats: 55, carbohydrates: 1, sugars: 1, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Blé Ebly portion 65 gr sec',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 350.4, proteins: 12.16, fats: 1.28, carbohydrates: 69.76, sugars: 1.28, fibers: 5.76, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Brocoli surgelé Bio U',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 14, proteins: 1.8, fats: 0.5, carbohydrates: 0.3, sugars: 0.5, fibers: 3, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Butternut',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 45, proteins: 1.23, fats: 0.07, carbohydrates: 10.5, sugars: 3.2, fibers: 2, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Cacao non sucré VAN HOUTEN',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 379, proteins: 20, fats: 21, carbohydrates: 11, sugars: 0.9, fibers: 28, salt: 0},
        needReview: false,
        category: 'Épice',
    },
    {
        name: 'Carotte',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 40.2, proteins: 0.63, fats: 0, carbohydrates: 7.59, sugars: 0.4, fibers: 2.7, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Champignons',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 21.7, proteins: 2.37, fats: 0.23, carbohydrates: 1.88, sugars: 0, fibers: 1.72, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: "Chèvre - P'tit Ste Maure cendré 170 g",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 304, proteins: 19, fats: 25, carbohydrates: 0.7, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Chipolatas U (par 6, 330 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 272, proteins: 15, fats: 23, carbohydrates: 1.3, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Charcuterie',
    },
    {
        name: 'Chocolat noir tablette 100 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 593, proteins: 9.5, fats: 45.1, carbohydrates: 32.4, sugars: 24.4, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit chocolaté',
    },
    {
        name: 'Chocolat pâtissier 71 %',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 601, proteins: 7, fats: 46, carbohydrates: 32, sugars: 28, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit chocolaté',
    },
    {
        name: 'Chocolat Pépites Koro 70%',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 555, proteins: 9.2, fats: 46, carbohydrates: 31, sugars: 1, fibers: 10, salt: 0},
        needReview: false,
        category: 'Produit chocolaté',
    },
    {
        name: 'Chou kale',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 50, proteins: 3.3, fats: 0.7, carbohydrates: 10, sugars: 0, fibers: 2.4, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Chou-fleur surgelé',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 19, proteins: 1.6, fats: 0.5, carbohydrates: 1.9, sugars: 1.9, fibers: 2.5, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Comté Bio 6 mois',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 418, proteins: 27, fats: 35, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Concombre, pulpe, cru',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 14.7, proteins: 0.56, fats: 0, carbohydrates: 2.23, sugars: 0, fibers: 0.8, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Coquillettes 1/2 Complètes',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 355, proteins: 12, fats: 1.9, carbohydrates: 70, sugars: 3.8, fibers: 4.7, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Cottage Cheese Biocoop 200 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 105, proteins: 13, fats: 4.5, carbohydrates: 3.5, sugars: 3.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Courgette, pulpe et peau, crue',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 16.5, proteins: 1.23, fats: 0.26, carbohydrates: 1.8, sugars: 0, fibers: 1.05, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Couscous 1/2 complet',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 400, proteins: 11, fats: 2, carbohydrates: 71, sugars: 3, fibers: 5, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Crème liquide entière U bio',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 294, proteins: 2.4, fats: 30, carbohydrates: 3.5, sugars: 3.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Crème Soja liquide',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 132, proteins: 3.1, fats: 12, carbohydrates: 3.4, sugars: 1.2, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier végétal',
    },
    {
        name: 'Crevettes',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 74, proteins: 16, fats: 0.8, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Fruits de mer',
    },
    {
        name: 'Crozets',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 335, proteins: 12.6, fats: 3.1, carbohydrates: 70.6, sugars: 2, fibers: 6, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Dés de jambon Herta Nature  2x75 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 98, proteins: 18, fats: 2, carbohydrates: 1.9, sugars: 1.5, fibers: 0.5, salt: 0},
        needReview: false,
        category: 'Charcuterie',
    },
    {
        name: 'Double concentré de tomates 3x70g',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 98, proteins: 4.7, fats: 0.5, carbohydrates: 15.7, sugars: 13.2, fibers: 3.6, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Epinards en branche surgelés',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 54, proteins: 5.9, fats: 0.5, carbohydrates: 8.8, sugars: 3.9, fibers: 6.5, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Farine T65',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 339, proteins: 12, fats: 0.7, carbohydrates: 69, sugars: 1.9, fibers: 4.3, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Farine T80',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 350, proteins: 10, fats: 1.9, carbohydrates: 71, sugars: 2.2, fibers: 4.6, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Faux filet',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 151, proteins: 22, fats: 6.7, carbohydrates: 0.6, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Feta',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 276, proteins: 16, fats: 23, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: "Flocons d'avoine",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 393, proteins: 12, fats: 8.8, carbohydrates: 61, sugars: 1, fibers: 11, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Fromage blanc nature 3% MG (100 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 74, proteins: 7.3, fats: 3, carbohydrates: 4.3, sugars: 4.3, fibers: 0.5, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Fromage Croque emmental x20 - 340 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 231, proteins: 13.5, fats: 17, carbohydrates: 6, sugars: 4.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Fromage de madame Loïc',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 252, proteins: 5.9, fats: 24, carbohydrates: 3, sugars: 3, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Fromage tartare',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 348, proteins: 7, fats: 34.5, carbohydrates: 2.3, sugars: 2.3, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Gnocchi à poêler U 300 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 189, proteins: 5.7, fats: 2.8, carbohydrates: 34, sugars: 0.5, fibers: 2.6, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Graines de courge',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 585, proteins: 37, fats: 46, carbohydrates: 2, sugars: 1.4, fibers: 6, salt: 0},
        needReview: false,
        category: 'Graines',
    },
    {
        name: 'Graines de lin',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 506, proteins: 23.9, fats: 36.6, carbohydrates: 6.6, sugars: 1.55, fibers: 0, salt: 0},
        needReview: false,
        category: 'Graines',
    },
    {
        name: 'Graines de pavot',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 520, proteins: 18, fats: 41.6, carbohydrates: 8.6, sugars: 3, fibers: 19.5, salt: 0},
        needReview: false,
        category: 'Graines',
    },
    {
        name: 'Graines de sésame',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 588, proteins: 18, fats: 50, carbohydrates: 10, sugars: 0.2, fibers: 12, salt: 0},
        needReview: false,
        category: 'Graines',
    },
    {
        name: 'Granola aux noix Koro',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 471, proteins: 14, fats: 25, carbohydrates: 45, sugars: 12, fibers: 8.5, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Granola Noix & Graines U Céréales',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 454, proteins: 13, fats: 18, carbohydrates: 56, sugars: 13, fibers: 7.7, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Haricots Blanc 280 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 109, proteins: 6.5, fats: 0.8, carbohydrates: 12, sugars: 0.6, fibers: 7, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Haricots noirs 230 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 95, proteins: 5.8, fats: 0.8, carbohydrates: 13.8, sugars: 0.6, fibers: 4.6, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Huile de tournesol',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 828, proteins: 0, fats: 92, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Huile',
    },
    {
        name: 'Jambons 4 tranches 140 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 116, proteins: 22, fats: 2.8, carbohydrates: 0.7, sugars: 0.7, fibers: 0, salt: 0},
        needReview: false,
        category: 'Charcuterie',
    },
    {
        name: 'Knacki (par 6 = 210 gr sans nitrite)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 264, proteins: 12, fats: 23, carbohydrates: 2.3, sugars: 1.8, fibers: 0.5, salt: 0},
        needReview: false,
        category: 'Charcuterie',
    },
    {
        name: 'Lait de noisettes',
        referenceUnit: 'ml',
        density: 1,
        nutrientsPer100: { energyKcal: 31, proteins: 0.6, fats: 2.9, carbohydrates: 0.6, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Boisson végétale',
    },
    {
        name: 'Lait demi-écrémé',
        referenceUnit: 'ml',
        density: 1,
        nutrientsPer100: { energyKcal: 45, proteins: 3.2, fats: 1.6, carbohydrates: 4.7, sugars: 4.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Lait Entier',
        referenceUnit: 'ml',
        density: 1,
        nutrientsPer100: { energyKcal: 64, proteins: 3.2, fats: 3.6, carbohydrates: 4.7, sugars: 4.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Lardons végétaux LA VIE (150g)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 218, proteins: 14, fats: 15, carbohydrates: 4.6, sugars: 1.2, fibers: 3.3, salt: 0},
        needReview: false,
        category: 'Produit végétal',
    },
    {
        name: 'Lasagnes PANZANI',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 361, proteins: 12, fats: 2, carbohydrates: 72, sugars: 3.7, fibers: 3.6, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Lentilles corails',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 328, proteins: 27.7, fats: 0.8, carbohydrates: 44.9, sugars: 1.29, fibers: 15.4, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Lentilles vertes',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 315, proteins: 24, fats: 1.3, carbohydrates: 45, sugars: 1, fibers: 14, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Levure de bière en paillettes',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 331, proteins: 47, fats: 4.3, carbohydrates: 15, sugars: 12, fibers: 22, salt: 0},
        needReview: false,
        category: 'Épice',
    },
    {
        name: 'Maïs sans sucre ajouté 140 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 77, proteins: 2.8, fats: 1.7, carbohydrates: 11, sugars: 5.2, fibers: 3.1, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Maizena',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 355, proteins: 0.5, fats: 0.5, carbohydrates: 86, sugars: 0.5, fibers: 1, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Mayonnaise',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 407, proteins: 1.2, fats: 70, carbohydrates: 1.6, sugars: 1.5, fibers: 0.5, salt: 0},
        needReview: false,
        category: 'Condiment',
    },
    {
        name: 'Meule (estimatif)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 412, proteins: 27, fats: 33, carbohydrates: 1.8, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Miel de printemps',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 331, proteins: 0.3, fats: 0, carbohydrates: 83, sugars: 83, fibers: 0, salt: 0},
        needReview: false,
        category: 'Sucre',
    },
    {
        name: 'Miso (sachet 22 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 89, proteins: 7.4, fats: 3.6, carbohydrates: 4.3, sugars: 4.1, fibers: 0, salt: 0},
        needReview: false,
        category: 'Condiment',
    },
    {
        name: 'Moutarde',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 368, proteins: 5.2, fats: 7.1, carbohydrates: 2.7, sugars: 2, fibers: 0, salt: 0},
        needReview: false,
        category: 'Condiment',
    },
    {
        name: 'Mozarella',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 280, proteins: 28, fats: 17, carbohydrates: 3.1, sugars: 1.2, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Navet',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 28, proteins: 0.9, fats: 0.1, carbohydrates: 6, sugars: 3.8, fibers: 1.8, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Noix de cajou, grillée à sec, non salée',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 617, proteins: 17.4, fats: 49, carbohydrates: 23.5, sugars: 11.8, fibers: 5.7, salt: 0},
        needReview: false,
        category: 'Noix',
    },
    {
        name: 'Nouilles en nids',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 316, proteins: 12, fats: 2, carbohydrates: 62, sugars: 3, fibers: 3, salt: 0},
        needReview: true,
        category: 'Céréale',
    },
    {
        name: 'Oeuf, cru 50 gr sans coquille',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 140, proteins: 12.7, fats: 9.83, carbohydrates: 0.27, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Oeuf',
    },
    {
        name: 'Pain Burger farine complète (87,5 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 270, proteins: 9.4, fats: 5, carbohydrates: 44, sugars: 4.8, fibers: 5.8, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Pain de mie U (500 g/24 tranches)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 258, proteins: 8.2, fats: 2.5, carbohydrates: 49, sugars: 3.4, fibers: 3.2, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Pain T65+T80 42gr (1/4 ème morceau)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 343, proteins: 11.2, fats: 1.47, carbohydrates: 69.8, sugars: 2.02, fibers: 4.42, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Parmesan',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 409, proteins: 31.1, fats: 31, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Patate douce, crue',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 86.3, proteins: 1.51, fats: 0.15, carbohydrates: 18.3, sugars: 12.7, fibers: 2.87, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Pâte brisée maison (280 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 467, proteins: 16.7, fats: 19, carbohydrates: 41, sugars: 3, fibers: 3, salt: 0},
        needReview: true,
        category: 'Céréale',
    },
    {
        name: 'Pesto aux fanes de radis (maison)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 435, proteins: 8, fats: 44, carbohydrates: 1, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Condiment',
    },
    {
        name: 'Petit Suisse 60 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 88, proteins: 9.3, fats: 3.9, carbohydrates: 3.8, sugars: 3.8, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Petits pois surgelés',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 75, proteins: 5.9, fats: 0.5, carbohydrates: 8.8, sugars: 3.9, fibers: 6.5, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Poireau, cru',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 32.3, proteins: 1.49, fats: 0.25, carbohydrates: 4.9, sugars: 0, fibers: 2.27, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Pois cassés (230 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 110, proteins: 3.5, fats: 0.7, carbohydrates: 18.6, sugars: 0.5, fibers: 5.8, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: 'Pois chiche (230 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 134, proteins: 7.1, fats: 2.4, carbohydrates: 21, sugars: 0.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Légumineuse',
    },
    {
        name: "Poivre",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 255, proteins: 15.95, fats: 3.26, carbohydrates: 44.5, sugars: 38.3, fibers: 26.5, salt: 0},
        needReview: false,
        category: 'Épice',
    },
    {
        name: "Poivron grillés à l'huile 190 gr",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 158, proteins: 0.9, fats: 15, carbohydrates: 4.1, sugars: 3.9, fibers: 2.6, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Poivron rouge, cru',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 36.6, proteins: 1.06, fats: 0, carbohydrates: 5.98, sugars: 0, fibers: 3.2, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Pomme (fruit)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 54.9, proteins: 0.5, fats: 0.5, carbohydrates: 11.7, sugars: 11.3, fibers: 2.5, salt: 0},
        needReview: false,
        category: 'Fruit',
    },
    {
        name: 'Pomme de terre crue',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 80.5, proteins: 2.16, fats: 0.18, carbohydrates: 16.2, sugars: 15.4, fibers: 1.8, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Porc, filet mignon, cuit',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 168, proteins: 26.1, fats: 7.1, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Potimarron',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 38, proteins: 1, fats: 0.3, carbohydrates: 6.88, sugars: 0, fibers: 1.8, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Poudre végétale 15 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 439, proteins: 80, fats: 6.8, carbohydrates: 11, sugars: 0.1, fibers: 0, salt: 0},
        needReview: false,
        category: 'Supplément',
    },
    {
        name: 'Poulet, blanc, cru',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 104, proteins: 23, fats: 1.3, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: "Poulet, cuisse, viande et peau, bouilli/cuit à l'eau",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 188, proteins: 26.1, fats: 9.1, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Protéines de soja Vantastic',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 332, proteins: 49, fats: 1.2, carbohydrates: 29, sugars: 8.6, fibers: 0, salt: 0},
        needReview: false,
        category: 'Supplément',
    },
    {
        name: 'Quinoa Trio en vrac',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 361, proteins: 11, fats: 6.5, carbohydrates: 59, sugars: 2.9, fibers: 13, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Reblochon petit 240 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 329, proteins: 21, fats: 27, carbohydrates: 0.5, sugars: 0.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Ricotta (250 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 164, proteins: 8, fats: 12, carbohydrates: 6, sugars: 4.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit laitier',
    },
    {
        name: 'Riz à sushi',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 346, proteins: 5.02, fats: 0.57, carbohydrates: 80.6, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Riz Basmati semi complet',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 355, proteins: 8.4, fats: 2.3, carbohydrates: 73, sugars: 0.5, fibers: 4.3, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Rôti de porc FLEURY MICHON 210 gr 6 tranches',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 127, proteins: 24, fats: 3, carbohydrates: 0.9, sugars: 0.9, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Salade de chou Sushi market (115 g)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 168, proteins: 1.1, fats: 5.6, carbohydrates: 28, sugars: 19, fibers: 0, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Sardines au naturel sans arêtes CONNETABLE 161g',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 158, proteins: 22, fats: 7.8, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Poisson',
    },
    {
        name: 'Soja crispies au cacao Koro',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 362, proteins: 58, fats: 1.9, carbohydrates: 28, sugars: 9.1, fibers: 1.8, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: "Son d'avoine Markal",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 334, proteins: 15, fats: 4.8, carbohydrates: 50, sugars: 2.3, fibers: 17, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Son de blé',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 279, proteins: 15.4, fats: 4.35, carbohydrates: 23.6, sugars: 20.9, fibers: 42, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Sucre de canne Blond',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 398, proteins: 0, fats: 0, carbohydrates: 99.5, sugars: 99.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Sucre',
    },
    {
        name: 'Tempeh à cuisiner 200 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 179, proteins: 19, fats: 9.4, carbohydrates: 0.5, sugars: 0.4, fibers: 0, salt: 0},
        needReview: false,
        category: 'Produit végétal',
    },
    {
        name: 'Thon entier au naturel 140 gr',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 109, proteins: 25, fats: 1, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Poisson',
    },
    {
        name: 'Tomate grappe, crue',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 20.1, proteins: 0.5, fats: 0, carbohydrates: 3.03, sugars: 0, fibers: 1.5, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Tomates entières en conserve 400 g',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 27, proteins: 1.1, fats: 0.2, carbohydrates: 4.2, sugars: 3.8, fibers: 1.1, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Tomates séchées bocal 140gr net égoutté',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 178, proteins: 3.6, fats: 11.6, carbohydrates: 11.4, sugars: 5.6, fibers: 6.9, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Tortilla de blé complete (géante 58 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 293, proteins: 9.1, fats: 6, carbohydrates: 47.8, sugars: 2.3, fibers: 5.5, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Tortilla de blé nature (grande 41 gr)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 299, proteins: 9.1, fats: 5.2, carbohydrates: 53.2, sugars: 2.1, fibers: 1.6, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Viande à bourguignon (macreuse)',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 119, proteins: 24, fats: 2.2, carbohydrates: 0.7, sugars: 0.7, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Viande hachée 5 %',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 125, proteins: 20, fats: 5, carbohydrates: 2.3, sugars: 0, fibers: 0, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Vinaigre pour sushi',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 112, proteins: 0, fats: 0, carbohydrates: 36, sugars: 33, fibers: 0, salt: 0},
        needReview: false,
        category: 'Condiment',
    },
    {
        name: 'Whey nutripure',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 380, proteins: 87, fats: 1.9, carbohydrates: 3, sugars: 0.5, fibers: 0, salt: 0},
        needReview: false,
        category: 'Supplément',
    },
    {
        name: 'Cordon Bleu poulet père dodu',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 201, proteins: 14, fats: 9.1, carbohydrates: 15, sugars: 1.5, fibers: 1.6, salt: 0},
        needReview: false,
        category: 'Viande',
    },
    {
        name: 'Coulis de tomates Tomacouli',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 27, proteins: 1.2, fats: 0.1, carbohydrates: 4.5, sugars: 3.9, fibers: 1.6, salt: 0},
        needReview: false,
        category: 'Légume',
    },
    {
        name: 'Spaghetti semi-complet biocoop',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 355, proteins: 12, fats: 1.9, carbohydrates: 70, sugars: 3.8, fibers: 4.7, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Poissons surgelés mix 600 g',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 115, proteins: 18, fats: 4.8, carbohydrates: 0.5, sugars: 0, fibers: 0.5, salt: 0},
        needReview: false,
        category: 'Poisson',
    },
    {
        name: "Farine d'épeautre T70",
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 344, proteins: 16, fats: 2.4, carbohydrates: 60, sugars: 6.7, fibers: 11, salt: 0},
        needReview: false,
        category: 'Céréale',
    },
    {
        name: 'Oeuf entier',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'inconnue',
    },
    {
        name: 'Eau',
        referenceUnit: 'ml',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Eau',
    },
    {
        name: 'Arôme de banane',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'inconnue',
    },
    {
        name: 'Psyllium',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'inconnue',
    },
    {
        name: 'Gruyère',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Produit laitier',
    },
    {
        name: 'Sel',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Oignon',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
    {
        name: 'Ail',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
    {
        name: 'Raz-el-Hanout',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Epices à couscous',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Paprika',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Curry',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Curcuma',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Gingembre',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Origan',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Cumin',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Jus de citron',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Condiment',
    },
    {
        name: 'Bouillon',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Condiment',
    },
    {
        name: 'Chou frisé',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
    {
        name: 'Huile de sésame',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Huile',
    },
    {
        name: 'Échalote',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
    {
        name: 'Piment',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Vinaigre balsamique',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Condiment',
    },
    {
        name: 'Cornichons',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
    {
        name: 'Ciboulette',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Herbe de provence',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Épice',
    },
    {
        name: 'Vinaigre de cidre',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Condiment',
    },
    {
        name: 'Laitue',
        referenceUnit: 'g',
        density: 1,
        nutrientsPer100: { energyKcal: 0, proteins: 0, fats: 0, carbohydrates: 0, sugars: 0, fibers: 0, salt: 0},
        needReview: true,
        category: 'Légume',
    },
];
