import { Ingredient } from '../src/api/ingredients/schemas/ingredient.schema';

export const seedIngredients: Ingredient[] = [
    {
        name: 'Amandes entières',
        kiloCalories: 600,
        proteins: 22.6,
        fats: 51.3,
        carbohydrates: 9.51,
        totalSugars: 4.2,
        fibers: 12.5,
    },
    {
        name: 'Aubergine, pulpe et peau, rôtie/cuite au four',
        kiloCalories: 33.8,
        proteins: 1.31,
        fats: 0,
        carbohydrates: 3.83,
        totalSugars: 0,
        fibers: 1.9,
    },
    {
        name: 'Bacon fumé JUSTIN BRIDOU, 16 tranches soit 160g',
        kiloCalories: 116,
        proteins: 23,
        fats: 2.5,
        carbohydrates: 0.3,
        totalSugars: 0.2,
        fibers: 0,
    },
    {
        name: 'Banane, pulpe, crue 100 gr',
        kiloCalories: 90.5,
        proteins: 1.06,
        fats: 0,
        carbohydrates: 19.7,
        totalSugars: 3.8,
        fibers: 2.7,
    },
    {
        name: 'Betterave en sachet',
        kiloCalories: 44,
        proteins: 0,
        fats: 0.1,
        carbohydrates: 7.2,
        totalSugars: 6.7,
        fibers: 0,
    },
    {
        name: 'Beurre de cacahuètes',
        kiloCalories: 635,
        proteins: 29,
        fats: 53,
        carbohydrates: 9.3,
        totalSugars: 4.5,
        fibers: 5.6,
    },
    {
        name: 'Beurre demi sel',
        kiloCalories: 726,
        proteins: 0.6,
        fats: 55,
        carbohydrates: 1,
        totalSugars: 1,
        fibers: 0,
    },
    {
        name: 'blé Ebly portion 65 gr sec',
        kiloCalories: 350.4,
        proteins: 12.16,
        fats: 1.28,
        carbohydrates: 69.76,
        totalSugars: 1.28,
        fibers: 5.76,
    },
    {
        name: 'Brocoli surgelé Bio U',
        kiloCalories: 14,
        proteins: 1.8,
        fats: 0.5,
        carbohydrates: 0.3,
        totalSugars: 0.5,
        fibers: 3,
    },
    {
        name: 'Butternut',
        kiloCalories: 45,
        proteins: 1.23,
        fats: 0.07,
        carbohydrates: 10.5,
        totalSugars: 3.2,
        fibers: 2,
    },
    {
        name: 'Cacao non sucré VAN HOUTEN',
        kiloCalories: 379,
        proteins: 20,
        fats: 21,
        carbohydrates: 11,
        totalSugars: 0.9,
        fibers: 28,
    },
    {
        name: 'Carotte',
        kiloCalories: 40.2,
        proteins: 0.63,
        fats: 0,
        carbohydrates: 7.59,
        totalSugars: 0.4,
        fibers: 2.7,
    },
    {
        name: 'Champignons',
        kiloCalories: 21.7,
        proteins: 2.37,
        fats: 0.23,
        carbohydrates: 1.88,
        totalSugars: 0,
        fibers: 1.72,
    },
    {
        name: "Chèvre - P'tit Ste Maure cendré 170 g",
        kiloCalories: 304,
        proteins: 19,
        fats: 25,
        carbohydrates: 0.7,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Chipolatas U (par 6, 330 gr)',
        kiloCalories: 272,
        proteins: 15,
        fats: 23,
        carbohydrates: 1.3,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Chocolat noir tablette 100 gr',
        kiloCalories: 593,
        proteins: 9.5,
        fats: 45.1,
        carbohydrates: 32.4,
        totalSugars: 24.4,
        fibers: 0,
    },
    {
        name: 'Chocolat pâtissier 71 %',
        kiloCalories: 601,
        proteins: 7,
        fats: 46,
        carbohydrates: 32,
        totalSugars: 28,
        fibers: 0,
    },
    {
        name: 'Chocolat Pépites Koro 70%',
        kiloCalories: 555,
        proteins: 9.2,
        fats: 46,
        carbohydrates: 31,
        totalSugars: 1,
        fibers: 10,
    },
    {
        name: 'Chou kale',
        kiloCalories: 50,
        proteins: 3.3,
        fats: 0.7,
        carbohydrates: 10,
        totalSugars: 0,
        fibers: 2.4,
    },
    {
        name: 'Chou-fleur surgelé',
        kiloCalories: 19,
        proteins: 1.6,
        fats: 0.5,
        carbohydrates: 1.9,
        totalSugars: 1.9,
        fibers: 2.5,
    },
    {
        name: 'Comté Bio 6 mois',
        kiloCalories: 418,
        proteins: 27,
        fats: 35,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Concombre, pulpe, cru',
        kiloCalories: 14.7,
        proteins: 0.56,
        fats: 0,
        carbohydrates: 2.23,
        totalSugars: 0,
        fibers: 0.8,
    },
    {
        name: 'Coquillettes 1/2 Complètes',
        kiloCalories: 355,
        proteins: 12,
        fats: 1.9,
        carbohydrates: 70,
        totalSugars: 3.8,
        fibers: 4.7,
    },
    {
        name: 'Cottage Cheese Biocoop 200 gr',
        kiloCalories: 105,
        proteins: 13,
        fats: 4.5,
        carbohydrates: 3.5,
        totalSugars: 3.5,
        fibers: 0,
    },
    {
        name: 'Courgette, pulpe et peau, crue',
        kiloCalories: 16.5,
        proteins: 1.23,
        fats: 0.26,
        carbohydrates: 1.8,
        totalSugars: 0,
        fibers: 1.05,
    },
    {
        name: 'Couscous 1/2 complet',
        kiloCalories: 400,
        proteins: 11,
        fats: 2,
        carbohydrates: 71,
        totalSugars: 3,
        fibers: 5,
    },
    {
        name: 'crème liquide entière U bio',
        kiloCalories: 294,
        proteins: 2.4,
        fats: 30,
        carbohydrates: 3.5,
        totalSugars: 3.5,
        fibers: 0,
    },
    {
        name: 'Crème Soja liquide',
        kiloCalories: 132,
        proteins: 3.1,
        fats: 12,
        carbohydrates: 3.4,
        totalSugars: 1.2,
        fibers: 0,
    },
    {
        name: 'Crevettes',
        kiloCalories: 74,
        proteins: 16,
        fats: 0.8,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Crozets',
        kiloCalories: 335,
        proteins: 12.6,
        fats: 3.1,
        carbohydrates: 70.6,
        totalSugars: 2,
        fibers: 6,
    },
    {
        name: 'Dés de jambon Herta Nature  2x75 gr',
        kiloCalories: 98,
        proteins: 18,
        fats: 2,
        carbohydrates: 1.9,
        totalSugars: 1.5,
        fibers: 0.5,
    },
    {
        name: 'Double concentré de tomates 3x70g',
        kiloCalories: 98,
        proteins: 4.7,
        fats: 0.5,
        carbohydrates: 15.7,
        totalSugars: 13.2,
        fibers: 3.6,
    },
    {
        name: 'Epinards en branche surgelés',
        kiloCalories: 54,
        proteins: 5.9,
        fats: 0.5,
        carbohydrates: 8.8,
        totalSugars: 3.9,
        fibers: 6.5,
    },
    {
        name: 'Farine T65',
        kiloCalories: 339,
        proteins: 12,
        fats: 0.7,
        carbohydrates: 69,
        totalSugars: 1.9,
        fibers: 4.3,
    },
    {
        name: 'Farine T80',
        kiloCalories: 350,
        proteins: 10,
        fats: 1.9,
        carbohydrates: 71,
        totalSugars: 2.2,
        fibers: 4.6,
    },
    {
        name: 'Faux filet',
        kiloCalories: 151,
        proteins: 22,
        fats: 6.7,
        carbohydrates: 0.6,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Feta',
        kiloCalories: 276,
        proteins: 16,
        fats: 23,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: "flocons d'avoine",
        kiloCalories: 393,
        proteins: 12,
        fats: 8.8,
        carbohydrates: 61,
        totalSugars: 1,
        fibers: 11,
    },
    {
        name: 'Fromage blanc nature 3% MG (100 gr)',
        kiloCalories: 74,
        proteins: 7.3,
        fats: 3,
        carbohydrates: 4.3,
        totalSugars: 4.3,
        fibers: 0.5,
    },
    {
        name: 'Fromage Croque emmental x20 - 340 gr',
        kiloCalories: 231,
        proteins: 13.5,
        fats: 17,
        carbohydrates: 6,
        totalSugars: 4.5,
        fibers: 0,
    },
    {
        name: 'Fromage de madame Loïc',
        kiloCalories: 252,
        proteins: 5.9,
        fats: 24,
        carbohydrates: 3,
        totalSugars: 3,
        fibers: 0,
    },
    {
        name: 'Fromage tartare',
        kiloCalories: 348,
        proteins: 7,
        fats: 34.5,
        carbohydrates: 2.3,
        totalSugars: 2.3,
        fibers: 0,
    },
    {
        name: 'Gnocchi à poêler U 300 gr',
        kiloCalories: 189,
        proteins: 5.7,
        fats: 2.8,
        carbohydrates: 34,
        totalSugars: 0.5,
        fibers: 2.6,
    },
    {
        name: 'graines de courge',
        kiloCalories: 585,
        proteins: 37,
        fats: 46,
        carbohydrates: 2,
        totalSugars: 1.4,
        fibers: 6,
    },
    {
        name: 'graines de lin',
        kiloCalories: 506,
        proteins: 23.9,
        fats: 36.6,
        carbohydrates: 6.6,
        totalSugars: 1.55,
        fibers: 0,
    },
    {
        name: 'graines de pavot',
        kiloCalories: 520,
        proteins: 18,
        fats: 41.6,
        carbohydrates: 8.6,
        totalSugars: 3,
        fibers: 19.5,
    },
    {
        name: 'graines de sésame',
        kiloCalories: 588,
        proteins: 18,
        fats: 50,
        carbohydrates: 10,
        totalSugars: 0.2,
        fibers: 12,
    },
    {
        name: 'Granola aux noix Koro',
        kiloCalories: 471,
        proteins: 14,
        fats: 25,
        carbohydrates: 45,
        totalSugars: 12,
        fibers: 8.5,
    },
    {
        name: 'Granola Noix & Graines U Céréales',
        kiloCalories: 454,
        proteins: 13,
        fats: 18,
        carbohydrates: 56,
        totalSugars: 13,
        fibers: 7.7,
    },
    {
        name: 'Haricots Blanc 280 gr',
        kiloCalories: 109,
        proteins: 6.5,
        fats: 0.8,
        carbohydrates: 12,
        totalSugars: 0.6,
        fibers: 7,
    },
    {
        name: 'Haricots noirs 230 gr',
        kiloCalories: 95,
        proteins: 5.8,
        fats: 0.8,
        carbohydrates: 13.8,
        totalSugars: 0.6,
        fibers: 4.6,
    },
    {
        name: 'huile de tournesol',
        kiloCalories: 828,
        proteins: 0,
        fats: 92,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Jambons 4 tranches 140 gr',
        kiloCalories: 116,
        proteins: 22,
        fats: 2.8,
        carbohydrates: 0.7,
        totalSugars: 0.7,
        fibers: 0,
    },
    {
        name: 'Knacki (par 6 = 210 gr sans nitrite)',
        kiloCalories: 264,
        proteins: 12,
        fats: 23,
        carbohydrates: 2.3,
        totalSugars: 1.8,
        fibers: 0.5,
    },
    {
        name: 'Lait de noisettes',
        kiloCalories: 31,
        proteins: 0.6,
        fats: 2.9,
        carbohydrates: 0.6,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Lait demi-écrémé',
        kiloCalories: 45,
        proteins: 3.2,
        fats: 1.6,
        carbohydrates: 4.7,
        totalSugars: 4.5,
        fibers: 0,
    },
    {
        name: 'Lait Entier',
        kiloCalories: 64,
        proteins: 3.2,
        fats: 3.6,
        carbohydrates: 4.7,
        totalSugars: 4.5,
        fibers: 0,
    },
    {
        name: 'lardons végétaux LA VIE (150g)',
        kiloCalories: 218,
        proteins: 14,
        fats: 15,
        carbohydrates: 4.6,
        totalSugars: 1.2,
        fibers: 3.3,
    },
    {
        name: 'Lasagnes PANZANI',
        kiloCalories: 361,
        proteins: 12,
        fats: 2,
        carbohydrates: 72,
        totalSugars: 3.7,
        fibers: 3.6,
    },
    {
        name: 'lentilles corails',
        kiloCalories: 328,
        proteins: 27.7,
        fats: 0.8,
        carbohydrates: 44.9,
        totalSugars: 1.29,
        fibers: 15.4,
    },
    {
        name: 'Lentilles vertes',
        kiloCalories: 315,
        proteins: 24,
        fats: 1.3,
        carbohydrates: 45,
        totalSugars: 1,
        fibers: 14,
    },
    {
        name: 'Levure de bière en paillettes',
        kiloCalories: 331,
        proteins: 47,
        fats: 4.3,
        carbohydrates: 15,
        totalSugars: 12,
        fibers: 22,
    },
    {
        name: 'Mais sans sucre ajouté 140 gr',
        kiloCalories: 77,
        proteins: 2.8,
        fats: 1.7,
        carbohydrates: 11,
        totalSugars: 5.2,
        fibers: 3.1,
    },
    {
        name: 'Maizena',
        kiloCalories: 355,
        proteins: 0.5,
        fats: 0.5,
        carbohydrates: 86,
        totalSugars: 0.5,
        fibers: 1,
    },
    {
        name: 'Mayonnaise',
        kiloCalories: 407,
        proteins: 1.2,
        fats: 70,
        carbohydrates: 1.6,
        totalSugars: 1.5,
        fibers: 0.5,
    },
    {
        name: 'Meule (estimatif)',
        kiloCalories: 412,
        proteins: 27,
        fats: 33,
        carbohydrates: 1.8,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Miel de printemps',
        kiloCalories: 331,
        proteins: 0.3,
        fats: 0,
        carbohydrates: 83,
        totalSugars: 83,
        fibers: 0,
    },
    {
        name: 'Miso (sachet 22 gr)',
        kiloCalories: 89,
        proteins: 7.4,
        fats: 3.6,
        carbohydrates: 4.3,
        totalSugars: 4.1,
        fibers: 0,
    },
    {
        name: 'Moutarde',
        kiloCalories: 368,
        proteins: 5.2,
        fats: 7.1,
        carbohydrates: 2.7,
        totalSugars: 2,
        fibers: 0,
    },
    {
        name: 'Mozarella',
        kiloCalories: 280,
        proteins: 28,
        fats: 17,
        carbohydrates: 3.1,
        totalSugars: 1.2,
        fibers: 0,
    },
    {
        name: 'Navet',
        kiloCalories: 28,
        proteins: 0.9,
        fats: 0.1,
        carbohydrates: 6,
        totalSugars: 3.8,
        fibers: 1.8,
    },
    {
        name: 'Noix de cajou, grillée à sec, non salée',
        kiloCalories: 617,
        proteins: 17.4,
        fats: 49,
        carbohydrates: 23.5,
        totalSugars: 11.8,
        fibers: 5.7,
    },
    {
        name: 'Nouilles en nids',
        kiloCalories: 315.6126245049802,
        proteins: 11.760470418816753,
        fats: 1.8000720028801152,
        carbohydrates: 62.402496099843994,
        totalSugars: 2.760110404416176,
        fibers: 2.760110404416176,
    },
    {
        name: 'Oeuf, cru 50 gr sans coquille',
        kiloCalories: 140,
        proteins: 12.7,
        fats: 9.83,
        carbohydrates: 0.27,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Pain Burger farine complète (87,5 gr)',
        kiloCalories: 270,
        proteins: 9.4,
        fats: 5,
        carbohydrates: 44,
        totalSugars: 4.8,
        fibers: 5.8,
    },
    {
        name: 'Pain de mie U (500 g/24 tranches)',
        kiloCalories: 258,
        proteins: 8.2,
        fats: 2.5,
        carbohydrates: 49,
        totalSugars: 3.4,
        fibers: 3.2,
    },
    {
        name: 'Pain T65+T80 42gr (1/4 ème morceau)',
        kiloCalories: 343,
        proteins: 11.2,
        fats: 1.47,
        carbohydrates: 69.8,
        totalSugars: 2.02,
        fibers: 4.42,
    },
    {
        name: 'Parmesan',
        kiloCalories: 409,
        proteins: 31.1,
        fats: 31,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Patate douce, crue',
        kiloCalories: 86.3,
        proteins: 1.51,
        fats: 0.15,
        carbohydrates: 18.3,
        totalSugars: 12.7,
        fibers: 2.87,
    },
    {
        name: 'Pâte brisée maison (280 gr)',
        kiloCalories: 466.64285714285717,
        proteins: 16.710714285714285,
        fats: 19.15357142857143,
        carbohydrates: 41.69642857142857,
        totalSugars: 3.9285714285714284,
        fibers: 3,
    },
    {
        name: 'Pesto aux fanes de radis (maison)',
        kiloCalories: 435,
        proteins: 8.147058823529411,
        fats: 43.9764705882353,
        carbohydrates: 1.1188235294117646,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Petit Suisse 60 gr',
        kiloCalories: 88,
        proteins: 9.3,
        fats: 3.9,
        carbohydrates: 3.8,
        totalSugars: 3.8,
        fibers: 0,
    },
    {
        name: 'Petits pois surgelés',
        kiloCalories: 75,
        proteins: 5.9,
        fats: 0.5,
        carbohydrates: 8.8,
        totalSugars: 3.9,
        fibers: 6.5,
    },
    {
        name: 'Poireau, cru',
        kiloCalories: 32.3,
        proteins: 1.49,
        fats: 0.25,
        carbohydrates: 4.9,
        totalSugars: 0,
        fibers: 2.27,
    },
    {
        name: 'Pois cassés (230 gr)',
        kiloCalories: 110,
        proteins: 3.5,
        fats: 0.7,
        carbohydrates: 18.6,
        totalSugars: 0.5,
        fibers: 5.8,
    },
    {
        name: 'Pois chiche (230 gr)',
        kiloCalories: 134,
        proteins: 7.1,
        fats: 2.4,
        carbohydrates: 21,
        totalSugars: 0.5,
        fibers: 0,
    },
    {
        name: "Poivron grillés à l'huile 190 gr",
        kiloCalories: 158,
        proteins: 0.9,
        fats: 15,
        carbohydrates: 4.1,
        totalSugars: 3.9,
        fibers: 2.6,
    },
    {
        name: 'Poivron rouge, cru',
        kiloCalories: 36.6,
        proteins: 1.06,
        fats: 0,
        carbohydrates: 5.98,
        totalSugars: 0,
        fibers: 3.2,
    },
    {
        name: 'Pomme (fruit)',
        kiloCalories: 54.9,
        proteins: 0.5,
        fats: 0.5,
        carbohydrates: 11.7,
        totalSugars: 11.3,
        fibers: 2.5,
    },
    {
        name: 'Pomme de terre crue',
        kiloCalories: 80.5,
        proteins: 2.16,
        fats: 0.18,
        carbohydrates: 16.2,
        totalSugars: 15.4,
        fibers: 1.8,
    },
    {
        name: 'Porc, filet mignon, cuit',
        kiloCalories: 168,
        proteins: 26.1,
        fats: 7.1,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Potimarron',
        kiloCalories: 38,
        proteins: 1,
        fats: 0.3,
        carbohydrates: 6.88,
        totalSugars: 0,
        fibers: 1.8,
    },
    {
        name: 'Poudre végétale 15 gr',
        kiloCalories: 439,
        proteins: 80,
        fats: 6.8,
        carbohydrates: 11,
        totalSugars: 0.1,
        fibers: 0,
    },
    {
        name: 'Poulet, blanc, cru',
        kiloCalories: 104,
        proteins: 23,
        fats: 1.3,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: "Poulet, cuisse, viande et peau, bouilli/cuit à l'eau",
        kiloCalories: 188,
        proteins: 26.1,
        fats: 9.1,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Protéines de soja Vantastic',
        kiloCalories: 332,
        proteins: 49,
        fats: 1.2,
        carbohydrates: 29,
        totalSugars: 8.6,
        fibers: 0,
    },
    {
        name: 'Quinoa Trio en vrac',
        kiloCalories: 361,
        proteins: 11,
        fats: 6.5,
        carbohydrates: 59,
        totalSugars: 2.9,
        fibers: 13,
    },
    {
        name: 'Reblochon petit 240 gr',
        kiloCalories: 329,
        proteins: 21,
        fats: 27,
        carbohydrates: 0.5,
        totalSugars: 0.5,
        fibers: 0,
    },
    {
        name: 'Ricotta (250 gr)',
        kiloCalories: 164,
        proteins: 8,
        fats: 12,
        carbohydrates: 6,
        totalSugars: 4.5,
        fibers: 0,
    },
    {
        name: 'Riz à sushi',
        kiloCalories: 346,
        proteins: 5.02,
        fats: 0.57,
        carbohydrates: 80.6,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Riz Basmati semi complet',
        kiloCalories: 355,
        proteins: 8.4,
        fats: 2.3,
        carbohydrates: 73,
        totalSugars: 0.5,
        fibers: 4.3,
    },
    {
        name: 'Rôti de porc FLEURY MICHON 210 gr 6 tranches',
        kiloCalories: 127,
        proteins: 24,
        fats: 3,
        carbohydrates: 0.9,
        totalSugars: 0.9,
        fibers: 0,
    },
    {
        name: 'Salade de chou Sushi market (115 g)',
        kiloCalories: 168,
        proteins: 1.1,
        fats: 5.6,
        carbohydrates: 28,
        totalSugars: 19,
        fibers: 0,
    },
    {
        name: 'Sardines au naturel sans arêtes CONNETABLE 161g',
        kiloCalories: 158,
        proteins: 22,
        fats: 7.8,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Soja crispies au cacao Koro',
        kiloCalories: 362,
        proteins: 58,
        fats: 1.9,
        carbohydrates: 28,
        totalSugars: 9.1,
        fibers: 1.8,
    },
    {
        name: "Son d'avoine Markal",
        kiloCalories: 334,
        proteins: 15,
        fats: 4.8,
        carbohydrates: 50,
        totalSugars: 2.3,
        fibers: 17,
    },
    {
        name: 'Son de blé',
        kiloCalories: 279,
        proteins: 15.4,
        fats: 4.35,
        carbohydrates: 23.6,
        totalSugars: 20.9,
        fibers: 42,
    },
    {
        name: 'Sucre de canne Blond',
        kiloCalories: 398,
        proteins: 0,
        fats: 0,
        carbohydrates: 99.5,
        totalSugars: 99.5,
        fibers: 0,
    },
    {
        name: 'Tempeh à cuisiner 200 gr',
        kiloCalories: 179,
        proteins: 19,
        fats: 9.4,
        carbohydrates: 0.5,
        totalSugars: 0.4,
        fibers: 0,
    },
    {
        name: 'Thon entier au naturel 140 gr',
        kiloCalories: 109,
        proteins: 25,
        fats: 1,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Tomate grappe, crue',
        kiloCalories: 20.1,
        proteins: 0.5,
        fats: 0,
        carbohydrates: 3.03,
        totalSugars: 0,
        fibers: 1.5,
    },
    {
        name: 'Tomates entières en conserve 400 g',
        kiloCalories: 27,
        proteins: 1.1,
        fats: 0.2,
        carbohydrates: 4.2,
        totalSugars: 3.8,
        fibers: 1.1,
    },
    {
        name: 'Tomates séchées bocal 140gr net égoutté',
        kiloCalories: 178,
        proteins: 3.6,
        fats: 11.6,
        carbohydrates: 11.4,
        totalSugars: 5.6,
        fibers: 6.9,
    },
    {
        name: 'Tortilla de blé complete (géante 58 gr)',
        kiloCalories: 293,
        proteins: 9.1,
        fats: 6,
        carbohydrates: 47.8,
        totalSugars: 2.3,
        fibers: 5.5,
    },
    {
        name: 'Tortilla de blé nature (grande 41 gr)',
        kiloCalories: 299,
        proteins: 9.1,
        fats: 5.2,
        carbohydrates: 53.2,
        totalSugars: 2.1,
        fibers: 1.6,
    },
    {
        name: 'Viande à bourguignon (macreuse)',
        kiloCalories: 119,
        proteins: 24,
        fats: 2.2,
        carbohydrates: 0.7,
        totalSugars: 0.7,
        fibers: 0,
    },
    {
        name: 'Viande hachée 5 %',
        kiloCalories: 125,
        proteins: 20,
        fats: 5,
        carbohydrates: 2.3,
        totalSugars: 0,
        fibers: 0,
    },
    {
        name: 'Vinaigre pour sushi',
        kiloCalories: 112,
        proteins: 0,
        fats: 0,
        carbohydrates: 36,
        totalSugars: 33,
        fibers: 0,
    },
    {
        name: 'Whey nutripure',
        kiloCalories: 380,
        proteins: 87,
        fats: 1.9,
        carbohydrates: 3,
        totalSugars: 0.5,
        fibers: 0,
    },
    {
        name: 'cordon Bleu poulet père dodu',
        kiloCalories: 201,
        proteins: 14,
        fats: 9.1,
        carbohydrates: 15,
        totalSugars: 1.5,
        fibers: 1.6,
    },
    {
        name: 'Coulis de tomates Tomacouli',
        kiloCalories: 27,
        proteins: 1.2,
        fats: 0.1,
        carbohydrates: 4.5,
        totalSugars: 3.9,
        fibers: 1.6,
    },
    {
        name: 'Spaghetti semi-complet biocoop',
        kiloCalories: 355,
        proteins: 12,
        fats: 1.9,
        carbohydrates: 70,
        totalSugars: 3.8,
        fibers: 4.7,
    },
    {
        name: 'Poissons surgelés mix 600 g',
        kiloCalories: 115,
        proteins: 18,
        fats: 4.8,
        carbohydrates: 0.5,
        totalSugars: 0,
        fibers: 0.5,
    },
    {
        name: "Farine d'épeautre T70",
        kiloCalories: 344,
        proteins: 16,
        fats: 2.4,
        carbohydrates: 60,
        totalSugars: 6.7,
        fibers: 11,
    },
    {
        name: 'Oeuf entier',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Eau',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Arôme de banane',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Psyllium',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Gruyère',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Sel',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Oignon',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Ail',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Raz-el-Hanout',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Epices à couscous',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Paprika',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Curry',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Curcuma',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Gingembre',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Origan',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Cumin',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Jus de citron',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Bouillon',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Chou frisé',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Huile de sésame',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Échalote',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Piment',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Vinaigre balsamique',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Cornichons',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Ciboulette',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Herbe de provence',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Vinaigre de cidre',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
    {
        name: 'Laitue',
        kiloCalories: 0,
        proteins: 0,
        fats: 0,
        carbohydrates: 0,
        totalSugars: 0,
        fibers: 0,
        needReview: true,
    },
];
